### ISSUE TITLE
Is this a good place to drop suggestions?

### ISSUE THREAD

**Issue by imoBooze** [MycophobiaSC/Gamma-Legion#1]
Hi, I am loving this mod!  I see that this repository is for the translated version, so I am wondering if this is the right place to put suggestions.

**Comment by MycophobiaSC** [comment]
> Hi, I am loving this mod! I see that this repository is for the translated version, so I am wondering if this is the right place to put suggestions.

As I am only the translator and not the modder, I dont check github often unless is to post a release, I suggest you reach out to me or the modder Yisic (though his english is not very good) on Discord. I may also prepare a forum post later on the Fractual Forum (probably this weekend)

**Comment by imoBooze** [comment]
I see, thank you!
